basePath: /
host: ws-dani.herokuapp.com
info:
  contact:
    email: 1214050@std.ac.id
    name: API Support
    url: https://github.com/daniferdinandall
  description: This is a sample swagger for Fiber
  title: TES SWAG
  version: "1.0"
paths: {}
schemes:
- https
- http
swagger: "2.0"
